main:
  - identifier: blog
    name: Blog
    weight: 4
    params:
      icon:
        vendor: fas
        name: blog

  - name: Support
    identifier: support
    weight: 100
    url: https://github.com/hbstack
    params:
      header: The HB support community.
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: Documentation
    parent: support
    url: https://hbstack.dev/
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: The documentations.

  - name: GitHub
    parent: support
    url: https://github.com/hbstack
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: Discussion
    parent: support
    url: https://github.com/orgs/hbstack/discussions
    weight: 12
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: green
      description: Ask questions and share your ideas.

  - name: Bug Report
    parent: support
    url: https://github.com/orgs/hbstack/discussions/new?category=issues-and-bugs
    weight: 13
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red
      description: Tell us about a bug or issue.

  - name: Feature Request
    parent: support
    url: https://github.com/orgs/hbstack/discussions/new?category=ideas
    weight: 14
    params:
      icon:
        vendor: font-awesome-regular
        name: lightbulb
        color: orange
      description: Suggest new or updated features.
  
  - name: Mastodon
    parent: support
    url: https://techhub.social/@hbstack
    weight: 16
    params:
      icon:
        vendor: simple
        name: mastodon
      description: Follow us on Mastodon to get latest updates.
footer:
- identifier: c
  name: Company
- name: About Us
  params:
    icon:
      color: blue
      name: people-fill
      vendor: bootstrap
  parent: c
  url: '#c-1'
- name: Contact
  params:
    icon:
      color: blue
      name: inbox-fill
      vendor: bootstrap
  parent: c
  url: '#c-2'
- name: Meetups
  params:
    icon:
      color: blue
      name: person-raised-hand
      vendor: bootstrap
  parent: c
  url: '#c-3'
- identifier: a
  name: Events
- name: Ongoing
  params:
    icon:
      color: '#712cf9'
      name: arrow-right-circle-fill
      vendor: bootstrap
  parent: a
  url: '#a-1'
- name: Coming Soon
  params:
    icon:
      color: '#712cf9'
      name: arrow-up-circle-fill
      vendor: bootstrap
  parent: a
  url: '#a-2'
- name: Past
  params:
    icon:
      color: '#712cf9'
      name: arrow-down-circle-fill
      vendor: bootstrap
  parent: a
  url: '#a-3'
- identifier: b
  name: Resources
- name: Games
  params:
    icon:
      color: green
      name: display
      vendor: bootstrap
  parent: b
  url: '#b-1'
- name: Wiki
  params:
    icon:
      color: green
      name: book-half
      vendor: bootstrap
  parent: b
  url: '#b-2'
- name: Blog
  params:
    icon:
      color: green
      name: journal-richtext
      vendor: bootstrap
  parent: b
  url: '#b-3'
- identifier: d
  name: Support
- name: Contribute
  params:
    icon:
      color: red
      name: pencil-square
      vendor: bootstrap
  parent: d
  url: '#d-1'
- name: Donate
  params:
    icon:
      color: red
      name: currency-exchange
      vendor: bootstrap
  parent: d
  url: '#d-2'
- name: Share the Word
  params:
    icon:
      color: red
      name: person-hearts
      vendor: bootstrap
  parent: d
  url: '#d-3'

