main:
  - identifier: blog
    name: Blog
    weight: 4
    params:
      icon:
        vendor: fas
        name: blog

  - name: Support
    identifier: support
    weight: 100
    url: https://github.com/hbstack
    params:
      header: The HB support community.
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: Documentations
    parent: support
    url: https://hbstack.dev/
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: The documentations.

  - name: GitHub
    parent: support
    url: https://github.com/hbstack
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: Discussion
    parent: support
    url: https://github.com/orgs/hbstack/discussions
    weight: 12
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: green
      description: Ask questions and share your ideas.

  - name: Bug Report
    parent: support
    url: https://github.com/orgs/hbstack/discussions/new?category=issues-and-bugs
    weight: 13
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red
      description: Tell us about a bug or issue.

  - name: Feature Request
    parent: support
    url: https://github.com/orgs/hbstack/discussions/new?category=ideas
    weight: 14
    params:
      icon:
        vendor: font-awesome-regular
        name: lightbulb
        color: orange
      description: Suggest new or updated features.
  
  - name: Mastodon
    parent: support
    url: https://techhub.social/@hbstack
    weight: 16
    params:
      icon:
        vendor: simple
        name: mastodon
      description: Follow us on Mastodon to get latest updates.
footer:
- identifier: a
  name: A
- name: A-1
  params:
    icon:
      color: '#712cf9'
      name: 1-square
      vendor: bootstrap
  parent: a
  url: '#a-1'
- name: A-2
  params:
    icon:
      color: '#712cf9'
      name: 2-square
      vendor: bootstrap
  parent: a
  url: '#a-2'
- identifier: b
  name: B
- name: B-1
  params:
    icon:
      color: green
      name: 1-square
      vendor: bootstrap
  parent: b
  url: '#b-1'
- name: B-2
  params:
    icon:
      color: green
      name: 2-square
      vendor: bootstrap
  parent: b
  url: '#b-2'
- identifier: c
  name: C
- name: C-1
  params:
    icon:
      color: blue
      name: 1-square
      vendor: bootstrap
  parent: c
  url: '#c-1'
- name: C-2
  params:
    icon:
      color: blue
      name: 2-square
      vendor: bootstrap
  parent: c
  url: '#c-2'
- identifier: d
  name: D
- name: D-1
  params:
    icon:
      color: red
      name: 1-square
      vendor: bootstrap
  parent: d
  url: '#d-1'
- name: D-2
  params:
    icon:
      color: red
      name: 2-square
      vendor: bootstrap
  parent: d
  url: '#d-2'

